=== PaymulovaTatyana/XML_ITMO/Exercise2/lessons.dtd
<?xml version = "1.0" encoding = "utf-8" ?>
<!ELEMENT lessons (lesson*)>
<!ELEMENT lesson (LessonName, ProfName, ProfLastName, ProfPatronymicName, StartDateEducation, FinishDateEducation)> 
<!ELEMENT LessonName (#PCDATA)> 
<!ELEMENT ProfName (#PCDATA)> 
<!ELEMENT ProfLastName (#PCDATA)> 
<!ELEMENT ProfPatronymicName (#PCDATA)> 
<!ELEMENT StartDateEducation (#PCDATA)> 
<!ELEMENT FinishDateEducation (#PCDATA)>

=== PaymulovaTatyana/XML_ITMO/Exercise2/lessons.xml
<?xml version = "1.0" encoding = "utf-8" ?>
<!DOCTYPE lessons SYSTEM 'lessons.dtd'>
<lessons>
	<lesson>
		<LessonName>Разработка Windows-приложений на С#</LessonName>
		<ProfName>Антон</ProfName>
		<ProfLastName>Смольянинов</ProfLastName>
		<ProfPatronymicName>Валентинович</ProfPatronymicName>
		<StartDateEducation>21.12.2020</StartDateEducation>
		<FinishDateEducation>15.01.2021 </FinishDateEducation>		
	</lesson>
	<lesson>
		<LessonName>Основы технологий разметки HTML, XML</LessonName>
		<ProfName>Антон</ProfName>
		<ProfLastName>Смольянинов</ProfLastName>
		<ProfPatronymicName>Валентинович</ProfPatronymicName>
		<StartDateEducation>18.01.2021</StartDateEducation>
		<FinishDateEducation>22.01.2021 </FinishDateEducation>
	</lesson>
	<lesson >
		<LessonName>Прошраммирование на Python</LessonName>
		<ProfName>Никита</ProfName>
		<ProfLastName>Осипов</ProfLastName>
		<ProfPatronymicName>Алексеевич</ProfPatronymicName>
		<StartDateEducation>25.01.2021</StartDateEducation>
		<FinishDateEducation>05.02.2021 </FinishDateEducation>
	</lesson>
</lessons>
